import test from 'node:test';import assert from 'node:assert/strict';import worker from '../src/worker.mjs';import {createEnv} from '../scripts/local-env.mjs';import {withTestCredentials} from '../scripts/test-credentials.mjs';
test('maintenance blocks visitors and mutations, preserves admin recovery, and reopens without data loss',async()=>{const env=await withTestCredentials(createEnv());env.ASSETS={fetch:async()=>new Response('Page',{headers:{'Content-Type':'text/html'}})};try{
const req=(p,m='GET',d,c='',origin='https://prisma.test')=>worker.fetch(new Request('https://prisma.test'+p,{method:m,headers:{Cookie:c,Origin:origin,'X-Prisma-Admin':'1','Content-Type':'application/json'},...(d?{body:JSON.stringify(d)}:{})}),env);
const login=async(role,login,password)=>req('/api/auth/login','POST',{role,login,password});let r=await login('admin','111111','123456');let admin=r.headers.get('set-cookie').split(';')[0];r=await login('collaborator','222222','654321');const collab=r.headers.get('set-cookie').split(';')[0];
assert.equal((await req('/')).status,200);assert.equal((await req('/api/admin/maintenance')).status,403);assert.equal((await req('/api/admin/maintenance','PUT',{enabled:true},collab)).status,403);
const config={enabled:true,message:'Volto em breve <script>alert(1)</script>',return_note:'Hoje às 18h',version:0};assert.equal((await req('/api/admin/maintenance','PUT',config,admin,'https://bad.test')).status,403);
r=await req('/api/admin/maintenance','PUT',config,admin);assert.equal(r.status,200);const saved=await r.json();assert.equal(saved.version,1);
for(const p of ['/','/eventos','/events.html','/ingressos','/voce-fala','/colaborador','/collaborator.html','/media/abc','/documents/abc','/unknown']){r=await req(p,'GET',null,collab);assert.equal(r.status,503,p);const html=await r.text();assert.ok(html.includes('Estamos em'));assert.ok(html.includes('&lt;script&gt;'));assert.ok(!html.includes('<script>alert(1)</script>'));assert.equal(r.headers.get('Cache-Control'),'private, no-store');}
assert.equal((await req('/','HEAD')).status,503);assert.equal(await(await req('/','HEAD')).text(),'');
for(const p of ['/api/proposals','/api/tickets/orders','/api/collaborator/messages']){r=await req(p,'POST',{},collab);assert.equal(r.status,503,p);assert.equal((await r.json()).maintenance,true);}
assert.equal((await login('collaborator','222222','654321')).status,503);assert.equal((await req('/api/events')).status,503);
assert.match(await(await req('/administrador')).text(),/login-form/);for(const p of ['/login.js','/style.css','/portal-common.js','/maintenance-client.js'])assert.equal((await req(p)).status,200);
r=await login('admin','111111','123456');assert.equal(r.status,200);admin=r.headers.get('set-cookie').split(';')[0];assert.equal((await req('/','GET',null,admin)).status,200);assert.match(await(await req('/administrador','GET',null,admin)).text(),/maintenance-form/);assert.equal((await req('/api/admin/events','GET',null,admin)).status,200);
assert.deepEqual(await(await req('/api/maintenance/status')).json(),{enabled:true,exempt:false});assert.deepEqual(await(await req('/api/maintenance/status','GET',null,admin)).json(),{enabled:true,exempt:true});
assert.equal((await req('/api/admin/maintenance','PUT',config,admin)).status,409);
r=await req('/api/admin/maintenance','PUT',{...saved,enabled:false},admin);assert.equal(r.status,200);assert.equal((await req('/')).status,200);assert.equal((await req('/api/events')).status,200);assert.equal((await req('/api/collaborator/workspace','GET',null,collab)).status,200);
}finally{env.close();}});
