import test from 'node:test';import assert from 'node:assert/strict';import worker from '../src/worker.mjs';import {createEnv} from '../scripts/local-env.mjs';import {withTestCredentials} from '../scripts/test-credentials.mjs';
test('ticket privacy, stock, retries, draft isolation and admin lifecycle',async()=>{const env=await withTestCredentials(createEnv());try{
 const req=(p,m='GET',d,cookie='',origin='https://prisma.test')=>worker.fetch(new Request('https://prisma.test'+p,{method:m,headers:{Cookie:cookie,Origin:origin,'Content-Type':'application/json','X-Prisma-Admin':'1'},...(d?{body:JSON.stringify(d)}:{})}),env);
 const login=async(role,login,password)=>(await req('/api/auth/login','POST',{role,login,password})).headers.get('set-cookie').split(';')[0];const admin=await login('admin','111111','123456'),collab=await login('collaborator','222222','654321');
 assert.equal((await req('/api/admin/tickets')).status,403);assert.equal((await req('/api/admin/tickets','GET',null,collab)).status,403);
 const event=(await(await req('/api/admin/events','POST',{name:'Teste de bilheteria',concept:'Evento fictício de teste'},admin)).json()).event;
 const sector=(await(await req('/api/admin/tickets/sectors','POST',{event_id:event.id,name:'Pista',capacity:2},admin)).json()).id;
 const makeLot=async name=>(await(await req('/api/admin/tickets/lots','POST',{sector_id:sector,name,capacity:2,price_cents:4500},admin)).json()).id;
 const lot=await makeLot('Lote 1'),lot2=await makeLot('Lote 2');const state=async()=>(await(await req('/api/admin/tickets','GET',null,admin)).json());
 let s=await state();assert.equal(s.sectors[0].active,0);for(const l of s.lots)assert.equal((await req('/api/admin/tickets/lots/'+l.id,'PUT',{...l,active:true},admin)).status,200);
 assert.equal((await req('/api/admin/tickets/sectors/'+sector,'PUT',{...s.sectors[0],active:true},admin)).status,200);
 assert.equal((await(await req('/api/tickets')).json()).lots.length,0);
 const orderData=lid=>({lot_id:lid,name:'Pessoa Fictícia',cpf:'00000000000',birth_date:'2000-01-01',fictional:true,request_key:crypto.randomUUID()});
 assert.equal((await req('/api/tickets/orders','POST',orderData(lot))).status,409);
 assert.equal((await req('/api/admin/events/'+event.id,'PUT',{...event,status:'published'},admin)).status,200);
 assert.equal((await(await req('/api/tickets')).json()).lots[0].available,2);
 assert.equal((await req('/api/tickets/orders','POST',{...orderData(lot),fictional:false})).status,400);
 assert.equal((await req('/api/tickets/orders','POST',{...orderData(lot),birth_date:'2000-02-31'})).status,400);
 assert.equal((await req('/api/tickets/orders','POST',orderData(lot),'','https://bad.test')).status,403);
 const d=orderData(lot),r=await req('/api/tickets/orders','POST',d);assert.equal(r.status,201);const receipt=await r.json();assert.equal(receipt.name,undefined);assert.equal(receipt.cpf,undefined);
 const repeat=await req('/api/tickets/orders','POST',d);assert.equal((await repeat.json()).id,receipt.id);assert.equal((await state()).orders.length,1);
 const results=await Promise.all([req('/api/tickets/orders','POST',orderData(lot2)),req('/api/tickets/orders','POST',orderData(lot))]);assert.deepEqual(results.map(r=>r.status).sort(),[201,409]);
 assert.ok((await(await req('/api/tickets')).json()).lots.every(l=>l.available===0));
 const detail='/api/admin/tickets/orders/'+receipt.id;assert.equal((await req(detail)).status,403);assert.equal((await req(detail,'GET',null,collab)).status,403);
 const o=(await(await req(detail,'GET',null,admin)).json()).order;assert.equal(o.name,d.name);assert.equal(o.birth_date,d.birth_date);assert.equal(o.cpf,d.cpf);assert.equal(o.request_key,undefined);
 s=await state();assert.equal(s.orders[0].cpf,undefined);assert.equal(s.orders[0].name,undefined);
 assert.equal((await req('/api/admin/tickets/sectors/'+sector,'PUT',{...s.sectors[0],capacity:1,active:true},admin)).status,409);
 assert.equal((await req('/api/admin/tickets/sectors/'+sector,'PUT',{...s.sectors[0],capacity:2,active:false},admin)).status,200);assert.equal((await(await req('/api/tickets')).json()).lots.length,0);
 s=await state();assert.equal((await req('/api/admin/tickets/sectors/'+sector,'PUT',{...s.sectors[0],active:true},admin)).status,200);
 assert.equal((await req(detail,'PUT',{status:'designed'},admin)).status,200);assert.equal((await req(detail,'PUT',{status:'cancelled'},admin)).status,200);assert.equal((await req(detail,'PUT',{status:'pending'},admin)).status,409);
 assert.equal((await(await req('/api/tickets')).json()).lots[0].available,1);
 const newD=orderData(lot);assert.equal((await req('/api/tickets/orders','POST',newD)).status,201);assert.equal((await req('/api/tickets/orders','POST',orderData(lot))).status,409);
 const publicBody=JSON.stringify(await(await req('/api/tickets')).json());assert.ok(!publicBody.includes('Pessoa Fictícia'));assert.ok(!publicBody.includes('00000000000'));
 }finally{env.close();}});
