import {one,run} from './db.mjs';
export const fail=(status,message)=>Object.assign(new Error(message),{status});
const hex=bytes=>Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,'0')).join('');
export const digest=async text=>hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)));
export async function hashPassword(password,salt=hex(crypto.getRandomValues(new Uint8Array(16)))){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:100000,hash:'SHA-256'},key,256);return salt+':'+hex(bits);}
export async function verify(password,hash){const actual=await hashPassword(password,hash.split(':')[0]);let diff=actual.length^hash.length;for(let i=0;i<actual.length;i++)diff|=actual.charCodeAt(i)^(hash.charCodeAt(i)||0);return diff===0;}
export function sixDigits(){const max=4294000000;let value;do{value=crypto.getRandomValues(new Uint32Array(1))[0];}while(value>=max);return String(value%1000000).padStart(6,'0');}
export async function seedAccounts(env){if(!env.INITIAL_ADMIN_LOGIN||!env.INITIAL_ADMIN_HASH||!env.INITIAL_COLLAB_LOGIN||!env.INITIAL_COLLAB_HASH)throw fail(503,'Os acessos ainda estão sendo configurados.');const now=new Date().toISOString();await run(env,'INSERT OR IGNORE INTO accounts (id,login,password_hash,role,name,created_at) VALUES (?,?,?,?,?,?)','owner',env.INITIAL_ADMIN_LOGIN,env.INITIAL_ADMIN_HASH,'admin','Administrador PRISMA',now);await run(env,'INSERT OR IGNORE INTO accounts (id,login,password_hash,role,name,created_at) VALUES (?,?,?,?,?,?)','initial-collaborator',env.INITIAL_COLLAB_LOGIN,env.INITIAL_COLLAB_HASH,'collaborator','Colaborador PRISMA',now);}
export async function currentAccount(request,env){const token=request.headers.get('cookie')?.split(';').map(s=>s.trim()).find(s=>s.startsWith('prisma_session='))?.slice(15);if(!token||!/^[a-f0-9]{64}$/.test(token))return null;return one(env,'SELECT accounts.id,accounts.role,accounts.name,accounts.email,accounts.city,accounts.about,accounts.login FROM sessions JOIN accounts ON accounts.id=sessions.account_id WHERE sessions.id=? AND sessions.expires>?',await digest(token),Date.now());}
export async function requireAccount(request,env,role){const account=await currentAccount(request,env);if(!account||role&&account.role!==role)throw fail(403,'Entre com o acesso correto para esta área.');return account;}
export function csrf(request){if(request.headers.get('x-prisma-admin')!=='1'||request.headers.get('origin')!==new URL(request.url).origin)throw fail(403,'Atualize a página e tente novamente.');}
export async function limited(env,key,max,windowMs){const now=Date.now();await run(env,'INSERT INTO limits (key,count,reset_at) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN reset_at<=? THEN 1 ELSE count+1 END,reset_at=CASE WHEN reset_at<=? THEN ? ELSE reset_at END',key,now+windowMs,now,now,now+windowMs);const limit=await one(env,'SELECT count FROM limits WHERE key=?',key);if(limit.count>max)throw fail(429,'Muitas tentativas. Aguarde 15 minutos e tente novamente.');}
export async function login(request,env,data){await seedAccounts(env);if(!/^\d{6}$/.test(data.login)||!/^\d{6}$/.test(data.password)||!['admin','collaborator'].includes(data.role))throw fail(400,'Use login e senha com exatamente 6 dígitos.');const ip=request.headers.get('cf-connecting-ip')||'unknown';await limited(env,'ip:'+await digest(ip),50,900000);await limited(env,'login:'+data.login,6,900000);const account=await one(env,'SELECT * FROM accounts WHERE login=?',data.login);const ok=await verify(data.password,account?.password_hash||env.INITIAL_ADMIN_HASH);if(!ok||!account||account.role!==data.role)throw fail(401,'Login ou senha incorretos para esta área.');await run(env,'DELETE FROM limits WHERE key=?','login:'+data.login);const token=hex(crypto.getRandomValues(new Uint8Array(32)));await run(env,'DELETE FROM sessions WHERE expires<?',Date.now());await run(env,'INSERT INTO sessions (id,account_id,expires) VALUES (?,?,?)',await digest(token),account.id,Date.now()+43200000);return {cookie:'prisma_session='+token+'; Path=/; HttpOnly; SameSite=Lax; Max-Age=43200'+(new URL(request.url).protocol==='https:'?'; Secure':''),redirect:account.role==='admin'?'/administrador':'/colaborador'};}
export async function logout(request,env){const token=request.headers.get('cookie')?.split(';').map(s=>s.trim()).find(s=>s.startsWith('prisma_session='))?.slice(15);if(token)await run(env,'DELETE FROM sessions WHERE id=?',await digest(token));return 'prisma_session=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0'+(new URL(request.url).protocol==='https:'?'; Secure':'');}
export async function createCollaborator(env,{name,email='',city=''}){let login;do{login=sixDigits();}while(await one(env,'SELECT id FROM accounts WHERE login=?',login));const password=sixDigits(),id=crypto.randomUUID(),hash=await hashPassword(password);await run(env,'INSERT INTO accounts (id,login,password_hash,role,name,email,city,about,created_at) VALUES (?,?,?,?,?,?,?,?,?)',id,login,hash,'collaborator',name,email,city,'',new Date().toISOString());return {id,login,password};}
