import {one,all,run,stmt} from './db.mjs';import {fail,currentAccount,requireAccount,csrf,login,logout,limited,digest,createCollaborator,sixDigits,hashPassword} from './auth.mjs';
const json=(data,status=200,headers={})=>Response.json(data,{status,headers:{'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff',...headers}});
const value=(v,max,required=false)=>{if(typeof v!=='string'||v.length>max||required&&!v.trim())throw fail(400,'Confira os campos obrigatórios e os limites de texto.');return v.trim();};
export async function bounded(request,max){const reader=request.body?.getReader();if(!reader)return new Uint8Array();const chunks=[];let size=0;while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>max){await reader.cancel();throw fail(413,'O envio ultrapassa o tamanho permitido.');}chunks.push(value);}const result=new Uint8Array(size);let offset=0;for(const c of chunks){result.set(c,offset);offset+=c.length;}return result;}
async function data(request){if(!request.headers.get('content-type')?.includes('application/json'))throw fail(415,'Envio inválido.');try{return JSON.parse(new TextDecoder().decode(await bounded(request,24000)));}catch(e){if(e.status)throw e;throw fail(400,'Dados inválidos.');}}
async function workspace(env,id){return {profile:await one(env,'SELECT id,name,email,city,about,login FROM accounts WHERE id=?',id),events:await all(env,'SELECT events.* FROM events JOIN collaborator_events ON collaborator_events.event_id=events.id WHERE collaborator_events.account_id=? ORDER BY events.updated_at DESC',id),messages:await all(env,'SELECT id,sender_role,body,created_at FROM messages WHERE account_id=? ORDER BY created_at,id LIMIT 500',id),documents:await all(env,'SELECT id,title,mime,size,created_at FROM documents WHERE account_id=? ORDER BY created_at DESC',id)};}
export async function portalApi(request,env,url){const path=url.pathname,method=request.method;
 if(path==='/api/auth/login'&&method==='POST'){csrf(request);const result=await login(request,env,await data(request));return json({redirect:result.redirect},200,{'Set-Cookie':result.cookie});}
 if(path==='/api/auth/logout'&&method==='POST'){csrf(request);return json({ok:true},200,{'Set-Cookie':await logout(request,env)});}
 if(path==='/api/auth/me'&&method==='GET')return json({account:await currentAccount(request,env)});
 if(path==='/api/proposals'&&method==='POST'){csrf(request);await limited(env,'proposal:'+await digest(request.headers.get('cf-connecting-ip')||'unknown'),10,900000);const d=await data(request),email=value(d.email,200,true);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw fail(400,'Informe um e-mail válido para contato.');const id=crypto.randomUUID();await run(env,'INSERT INTO proposals (id,name,email,city,state,title,description,status,created_at) VALUES (?,?,?,?,?,?,?,?,?)',id,value(d.name,160,true),email,value(d.city,120,true),value(d.state,80,true),value(d.title,160,true),value(d.description,6000,true),'pending',new Date().toISOString());return json({id,message:'Proposta recebida. A PRISMA poderá usar o contato informado para conversar sobre a ideia. O envio não confirma um evento nem uma parceria.'},201);}
 if(path==='/api/admin/proposals'){await requireAccount(request,env,'admin');if(method==='GET')return json({proposals:await all(env,'SELECT * FROM proposals ORDER BY created_at DESC')});}
 const review=path.match(/^\/api\/admin\/proposals\/([0-9a-f-]{36})\/(approve|decline)$/);if(review&&method==='POST'){await requireAccount(request,env,'admin');csrf(request);const p=await one(env,'SELECT * FROM proposals WHERE id=?',review[1]);if(!p||p.status!=='pending')throw fail(409,'Esta proposta já foi analisada ou não está disponível.');if(review[2]==='decline'){await run(env,"UPDATE proposals SET status='declined' WHERE id=? AND status='pending'",p.id);return json({ok:true});}const reserved=await run(env,"UPDATE proposals SET status='reviewing' WHERE id=? AND status='pending'",p.id);if(!reserved.meta.changes)throw fail(409,'Esta proposta está em análise em outra aba.');try{const credentials=await createCollaborator(env,{name:p.name,email:p.email,city:p.city+' / '+p.state});await run(env,"UPDATE proposals SET status='approved',account_id=? WHERE id=?",credentials.id,p.id);return json({credentials});}catch(error){await run(env,"UPDATE proposals SET status='pending' WHERE id=? AND status='reviewing'",p.id);throw error;}}
 if(path==='/api/admin/collaborators'){await requireAccount(request,env,'admin');if(method==='GET')return json({collaborators:await all(env,"SELECT id,login,name,email,city,about FROM accounts WHERE role='collaborator' ORDER BY created_at DESC")});if(method==='POST'){csrf(request);const d=await data(request);return json({credentials:await createCollaborator(env,{name:value(d.name,160,true)})},201);}}
 const c=path.match(/^\/api\/admin\/collaborators\/([a-z0-9-]+)(?:\/(event|reset|message))?$/);if(c){await requireAccount(request,env,'admin');const account=await one(env,"SELECT id FROM accounts WHERE id=? AND role='collaborator'",c[1]);if(!account)throw fail(404,'Colaborador não encontrado.');if(method==='GET'&&!c[2])return json(await workspace(env,c[1]));csrf(request);if(method==='POST'&&c[2]==='reset'){const password=sixDigits();await env.DB.batch([stmt(env,'UPDATE accounts SET password_hash=? WHERE id=?',await hashPassword(password),c[1]),stmt(env,'DELETE FROM sessions WHERE account_id=?',c[1])]);return json({credentials:{id:c[1],login:(await one(env,'SELECT login FROM accounts WHERE id=?',c[1])).login,password}});}if(method==='PUT'&&c[2]==='event'){const d=await data(request);if(d.event_id&&!await one(env,'SELECT id FROM events WHERE id=?',d.event_id))throw fail(400,'Evento não encontrado.');const statements=[stmt(env,'DELETE FROM collaborator_events WHERE account_id=?',c[1])];if(d.event_id)statements.push(stmt(env,'INSERT INTO collaborator_events (id,account_id,event_id) VALUES (?,?,?)',crypto.randomUUID(),c[1],d.event_id));await env.DB.batch(statements);return json({ok:true});}if(method==='POST'&&c[2]==='message'){const d=await data(request);await run(env,'INSERT INTO messages (id,account_id,sender_role,body,created_at) VALUES (?,?,?,?,?)',crypto.randomUUID(),c[1],'admin',value(d.body,4000,true),new Date().toISOString());return json({ok:true});}}
 if(path.startsWith('/api/collaborator/')){const account=await requireAccount(request,env,'collaborator');if(method!=='GET')csrf(request);if(path==='/api/collaborator/workspace'&&method==='GET')return json(await workspace(env,account.id));if(path==='/api/collaborator/profile'&&method==='PUT'){const d=await data(request);await run(env,'UPDATE accounts SET name=?,email=?,city=?,about=? WHERE id=?',value(d.name,160,true),value(d.email,200),value(d.city,200),value(d.about,4000),account.id);return json({ok:true});}if(path==='/api/collaborator/messages'&&method==='POST'){const d=await data(request);await run(env,'INSERT INTO messages (id,account_id,sender_role,body,created_at) VALUES (?,?,?,?,?)',crypto.randomUUID(),account.id,'collaborator',value(d.body,4000,true),new Date().toISOString());return json({ok:true});}if(path==='/api/collaborator/documents'&&method==='POST'){const count=await one(env,'SELECT COUNT(*) AS total FROM documents WHERE account_id=?',account.id);if(count.total>=30)throw fail(400,'Limite de 30 documentos atingido.');const raw=await bounded(request,11*1024*1024),form=await new Request(request.url,{method:'POST',headers:{'Content-Type':request.headers.get('content-type')},body:raw}).formData(),file=form.get('file'),title=value(form.get('title'),160,true);if(!file||typeof file.arrayBuffer!=='function'||file.size>10*1024*1024||!file.size)throw fail(400,'Envie um PDF ou imagem de até 10 MB.');const bytes=new Uint8Array(await file.arrayBuffer()),prefix=String.fromCharCode(...bytes.slice(0,12));const mime=prefix.startsWith('%PDF-')?'application/pdf':bytes[0]===137&&bytes[1]===80?'image/png':bytes[0]===255&&bytes[1]===216?'image/jpeg':prefix.startsWith('RIFF')&&prefix.endsWith('WEBP')?'image/webp':null;if(!mime)throw fail(415,'Use PDF, PNG, JPG ou WebP.');const id=crypto.randomUUID(),key='documents/'+account.id+'/'+id;await env.BUCKET.put(key,bytes,{httpMetadata:{contentType:mime}});try{await run(env,'INSERT INTO documents (id,account_id,title,storage_key,mime,size,created_at) VALUES (?,?,?,?,?,?,?)',id,account.id,title,key,mime,bytes.length,new Date().toISOString());}catch(error){await env.BUCKET.delete(key);throw error;}return json({ok:true},201);}}
 return null;
}
export async function documentResponse(request,env,id){const account=await requireAccount(request,env);const doc=await one(env,'SELECT * FROM documents WHERE id=?',id);if(!doc||account.role!=='admin'&&doc.account_id!==account.id)throw fail(404,'Documento não encontrado.');const file=await env.BUCKET.get(doc.storage_key);if(!file)throw fail(404,'Documento não encontrado.');const ext=doc.mime==='application/pdf'?'pdf':doc.mime.split('/')[1];return new Response(file.body,{headers:{'Content-Type':doc.mime,'Content-Disposition':'attachment; filename="documento-ficticio.'+ext+'"','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});}
