import {maintenanceGate,maintenanceApi} from './maintenance.mjs';
import {ticketsApi} from './tickets.mjs';
import {one,all,run,stmt} from './db.mjs';
import {adminPage,collaboratorPage,loginPage} from './pages.mjs';
import {currentAccount} from './auth.mjs';
import {portalApi,documentResponse,bounded} from './portal.mjs';
const json=(data,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});
const fault=(status,message)=>Object.assign(new Error(message),{status});
const idPattern=/^[0-9a-f-]{36}$/;
export async function isAdmin(request,env){return (await currentAccount(request,env))?.role==='admin';}
async function assertAdmin(request,env){if(!await isAdmin(request,env))throw fault(403,'Acesso reservado à administração da PRISMA.');}
function assertMutation(request){const origin=request.headers.get('origin');if(request.headers.get('x-prisma-admin')!=='1'||!origin||origin!==new URL(request.url).origin)throw fault(403,'Reabra o painel e tente novamente.');}
function text(value,max,required=false){if(typeof value!=='string'||value.length>max||required&&!value.trim())throw fault(400,'Confira os campos e os limites de texto.');return value.trim();}
async function body(request){if(!request.headers.get('content-type')?.includes('application/json'))throw fault(415,'Formato de envio inválido.');const raw=new TextDecoder().decode(await bounded(request,24000));try{return JSON.parse(raw);}catch{throw fault(400,'Dados inválidos.');}}
async function eventWithMedia(env,event){return {...event,media:await all(env,'SELECT id,event_id,mime,size,category,caption FROM media WHERE event_id = ? ORDER BY created_at,id',event.id)};}
const mimeFor=bytes=>bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71?'image/png':bytes[0]===255&&bytes[1]===216&&bytes[2]===255?'image/jpeg':String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP'?'image/webp':null;
async function api(request,env,url){const path=url.pathname,method=request.method;
 if(path==='/api/events'&&method==='GET'){const events=await all(env,"SELECT * FROM events WHERE status = ? ORDER BY updated_at DESC",'published');return json({events:await Promise.all(events.map(e=>eventWithMedia(env,e)))});}
 if(path.startsWith('/api/admin/')){await assertAdmin(request,env);if(method!=='GET')assertMutation(request);
 if(path==='/api/admin/events'&&method==='GET')return json({events:await all(env,'SELECT * FROM events ORDER BY updated_at DESC')});
 if(path==='/api/admin/events'&&method==='POST'){const data=await body(request),id=crypto.randomUUID(),now=new Date().toISOString();await run(env,'INSERT INTO events (id,name,concept,format,role,stage_type,stage_description,scenography,status,version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)',id,text(data.name,120,true),text(data.concept??'',6000),text(data.format??'',100),['apoio','patrocinio','realizacao'].includes(data.role)?data.role:'realizacao',text(data.stage_type??'',100),text(data.stage_description??'',4000),text(data.scenography??'',4000),'draft',1,now,now);return json({event:await eventWithMedia(env,await one(env,'SELECT * FROM events WHERE id = ?',id))},201);}
 const match=path.match(/^\/api\/admin\/events\/([0-9a-f-]{36})(\/media)?$/);
 if(match){const id=match[1],event=await one(env,'SELECT * FROM events WHERE id = ?',id);if(!event)throw fault(404,'Conceito não encontrado.');if(!match[2]&&method==='GET')return json({event:await eventWithMedia(env,event)});
 if(!match[2]&&method==='PUT'){const data=await body(request);if(!['draft','published'].includes(data.status)||!['apoio','patrocinio','realizacao'].includes(data.role)||!Number.isInteger(data.version))throw fault(400,'Dados inválidos.');const name=text(data.name,120,true),concept=text(data.concept,6000,data.status==='published');if(data.cover_id&&!(await one(env,'SELECT id FROM media WHERE id = ? AND event_id = ?',data.cover_id,id)))throw fault(400,'A capa deve pertencer a este evento.');const result=await run(env,'UPDATE events SET name=?,concept=?,format=?,role=?,stage_type=?,stage_description=?,scenography=?,status=?,cover_id=?,version=version+1,updated_at=? WHERE id=? AND version=?',name,concept,text(data.format,100),data.role,text(data.stage_type,100),text(data.stage_description,4000),text(data.scenography,4000),data.status,data.cover_id||null,new Date().toISOString(),id,data.version);if(!result.meta.changes)throw fault(409,'Este conceito foi atualizado em outra aba. Copie suas alterações antes de reabrir a versão atual.');return json({event:await eventWithMedia(env,await one(env,'SELECT * FROM events WHERE id = ?',id))});}
 if(match[2]&&method==='POST'){const length=Number(request.headers.get('content-length'));if(length>11*1024*1024)throw fault(413,'A imagem deve ter até 10 MB.');const count=await one(env,'SELECT COUNT(*) AS total FROM media WHERE event_id = ?',id);if(count.total>=20)throw fault(400,'Cada conceito pode ter até 20 imagens.');const form=await request.formData(),file=form.get('file'),category=form.get('category'),caption=text(form.get('caption')??'',400,true);if(!['design','palco','cenografia'].includes(category)||!file||typeof file.arrayBuffer!=='function'||file.size>10*1024*1024||file.size===0)throw fault(400,'Envie uma imagem JPG, PNG ou WebP de até 10 MB e uma descrição.');const bytes=new Uint8Array(await file.arrayBuffer()),mime=mimeFor(bytes);if(!mime)throw fault(415,'Use uma imagem JPG, PNG ou WebP.');const mediaId=crypto.randomUUID(),key='events/'+id+'/'+mediaId;await env.BUCKET.put(key,bytes,{httpMetadata:{contentType:mime}});try{await run(env,'INSERT INTO media (id,event_id,storage_key,mime,size,category,caption,created_at) VALUES (?,?,?,?,?,?,?,?)',mediaId,id,key,mime,bytes.length,category,caption,new Date().toISOString());}catch(e){await env.BUCKET.delete(key);throw e;}return json({media:{id:mediaId,event_id:id,mime,size:bytes.length,category,caption}},201);}}
 const mediaMatch=path.match(/^\/api\/admin\/media\/([0-9a-f-]{36})$/);if(mediaMatch&&method==='DELETE'){const media=await one(env,'SELECT * FROM media WHERE id = ?',mediaMatch[1]);if(!media)throw fault(404,'Imagem não encontrada.');await env.DB.batch([stmt(env,'UPDATE events SET cover_id=NULL,version=version+1 WHERE cover_id=?',media.id),stmt(env,'DELETE FROM media WHERE id=?',media.id)]);await env.BUCKET.delete(media.storage_key);return json({ok:true});}
 }
 throw fault(404,'Conteúdo não encontrado.');
}
export default {async fetch(request,env){try{const url=new URL(request.url);const maintenance=await maintenanceGate(request,env,url);if(maintenance)return maintenance;if(url.pathname.startsWith('/api/'))return await maintenanceApi(request,env,url)|| await ticketsApi(request,env,url)||await portalApi(request,env,url)||await api(request,env,url);
 if(url.pathname.startsWith('/documents/')){if(request.method!=='GET')throw fault(405,'Método não permitido.');return await documentResponse(request,env,url.pathname.slice(11));}
 if(url.pathname.startsWith('/media/')){if(!['GET','HEAD'].includes(request.method))throw fault(405,'Método não permitido.');const id=url.pathname.slice(7);if(!idPattern.test(id))throw fault(404,'Imagem não encontrada.');const media=await one(env,'SELECT media.*, events.status FROM media JOIN events ON events.id=media.event_id WHERE media.id=?',id);if(!media||media.status!=='published'&&!await isAdmin(request,env))throw fault(404,'Imagem não encontrada.');const file=await env.BUCKET.get(media.storage_key);if(!file)throw fault(404,'Imagem não encontrada.');return new Response(request.method==='HEAD'?null:file.body,{headers:{'Content-Type':media.mime,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});}
 if(!['GET','HEAD'].includes(request.method))throw fault(405,'Método não permitido.');const protectedRole=['/painel','/painel/','/admin.html','/administrador','/administrador/'].includes(url.pathname)?'admin':['/colaborador','/colaborador/','/collaborator.html'].includes(url.pathname)?'collaborator':null;
 if(protectedRole){const account=await currentAccount(request,env);const page=account?.role===protectedRole?(protectedRole==='admin'?adminPage:collaboratorPage):loginPage.replaceAll('__ROLE__',protectedRole).replaceAll('__TITLE__',protectedRole==='admin'?'Administrador':'Colaborador');return new Response(request.method==='HEAD'?null:page,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});}else if(url.pathname==='/ingressos'||url.pathname==='/ingressos/')url.pathname='/tickets.html';else if(url.pathname==='/eventos'||url.pathname==='/eventos/')url.pathname='/events.html';else if(url.pathname==='/voce-fala'||url.pathname==='/voce-fala/')url.pathname='/proposal.html';else if(url.pathname==='/')url.pathname='/index.html';
 if(url.pathname.startsWith('/.')||url.pathname.includes('..'))throw fault(404,'Conteúdo não encontrado.');const asset=await env.ASSETS.fetch(new Request(url,request));const response=new Response(asset.body,asset);response.headers.set('X-Content-Type-Options','nosniff');if(response.headers.get('Content-Type')?.includes('text/html'))response.headers.set('Cache-Control','private, no-store');if(url.pathname==='/admin.html')response.headers.set('Cache-Control','private, no-store');return response;
 }catch(error){console.error('PRISMA request failed',error.status??500,error.message);return json({error:error.status?error.message:'Não foi possível acessar os dados agora. Suas alterações continuam no formulário. Tente novamente.'},error.status??503);}}};
