import {sqliteTable,text,integer,index} from 'drizzle-orm/sqlite-core';
export const adminIdentity=sqliteTable('admin_identity',{key:text('key').primaryKey(),userId:text('user_id').notNull()});
export const events=sqliteTable('events',{id:text('id').primaryKey(),name:text('name').notNull(),concept:text('concept').notNull(),format:text('format').notNull(),role:text('role').notNull(),stageType:text('stage_type').notNull(),stageDescription:text('stage_description').notNull(),scenography:text('scenography').notNull(),status:text('status').notNull().default('draft'),coverId:text('cover_id'),version:integer('version').notNull().default(1),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('idx_events_status_updated').on(t.status,t.updatedAt)]);
export const media=sqliteTable('media',{id:text('id').primaryKey(),eventId:text('event_id').notNull().references(()=>events.id),storageKey:text('storage_key').notNull(),mime:text('mime').notNull(),size:integer('size').notNull(),category:text('category').notNull(),caption:text('caption').notNull(),createdAt:text('created_at').notNull()},t=>[index('idx_media_event').on(t.eventId)]);
export const accounts=sqliteTable('accounts',{id:text('id').primaryKey(),login:text('login').notNull().unique(),passwordHash:text('password_hash').notNull(),role:text('role').notNull(),name:text('name').notNull(),email:text('email').notNull().default(''),city:text('city').notNull().default(''),about:text('about').notNull().default(''),createdAt:text('created_at').notNull()});
export const sessions=sqliteTable('sessions',{id:text('id').primaryKey(),accountId:text('account_id').notNull().references(()=>accounts.id),expires:integer('expires').notNull()},t=>[index('idx_sessions_account').on(t.accountId)]);
export const limits=sqliteTable('limits',{key:text('key').primaryKey(),count:integer('count').notNull(),resetAt:integer('reset_at').notNull()});
export const proposals=sqliteTable('proposals',{id:text('id').primaryKey(),name:text('name').notNull(),email:text('email').notNull(),city:text('city').notNull(),state:text('state').notNull(),title:text('title').notNull(),description:text('description').notNull(),status:text('status').notNull().default('pending'),accountId:text('account_id').references(()=>accounts.id),createdAt:text('created_at').notNull()});
export const links=sqliteTable('collaborator_events',{id:text('id').primaryKey(),accountId:text('account_id').notNull().references(()=>accounts.id),eventId:text('event_id').notNull().references(()=>events.id)},t=>[index('idx_collaborator_events_account').on(t.accountId)]);
export const messages=sqliteTable('messages',{id:text('id').primaryKey(),accountId:text('account_id').notNull().references(()=>accounts.id),senderRole:text('sender_role').notNull(),body:text('body').notNull(),createdAt:text('created_at').notNull()},t=>[index('idx_messages_account_time').on(t.accountId,t.createdAt)]);
export const documents=sqliteTable('documents',{id:text('id').primaryKey(),accountId:text('account_id').notNull().references(()=>accounts.id),title:text('title').notNull(),storageKey:text('storage_key').notNull(),mime:text('mime').notNull(),size:integer('size').notNull(),createdAt:text('created_at').notNull()},t=>[index('idx_documents_account').on(t.accountId)]);
export const ticketSectors=sqliteTable('ticket_sectors',{id:text('id').primaryKey(),eventId:text('event_id').notNull().references(()=>events.id),name:text('name').notNull(),capacity:integer('capacity').notNull(),active:integer('active').notNull().default(0),version:integer('version').notNull().default(1),createdAt:text('created_at').notNull()},t=>[index('idx_ticket_sectors_event').on(t.eventId)]);
export const ticketLots=sqliteTable('ticket_lots',{id:text('id').primaryKey(),sectorId:text('sector_id').notNull().references(()=>ticketSectors.id),name:text('name').notNull(),capacity:integer('capacity').notNull(),priceCents:integer('price_cents').notNull(),active:integer('active').notNull().default(0),version:integer('version').notNull().default(1),createdAt:text('created_at').notNull()},t=>[index('idx_ticket_lots_sector').on(t.sectorId)]);
export const ticketOrders=sqliteTable('ticket_orders',{id:text('id').primaryKey(),requestKey:text('request_key').notNull().unique(),lotId:text('lot_id').notNull().references(()=>ticketLots.id),name:text('name').notNull(),cpf:text('cpf').notNull(),birthDate:text('birth_date').notNull(),status:text('status').notNull().default('pending'),eventName:text('event_name').notNull(),sectorName:text('sector_name').notNull(),lotName:text('lot_name').notNull(),priceCents:integer('price_cents').notNull(),createdAt:text('created_at').notNull()},t=>[index('idx_ticket_orders_lot_status').on(t.lotId,t.status),index('idx_ticket_orders_created').on(t.createdAt)]);

export const siteMaintenance=sqliteTable('site_maintenance',{id:text('id').primaryKey(),enabled:integer('enabled').notNull().default(0),message:text('message').notNull(),returnNote:text('return_note').notNull().default(''),version:integer('version').notNull().default(1)});
